version: "3.9"

services:

  # ── Django backend ───────────────────────────────────────────────────────────
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ig_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  postgres_data:
  mongodb_data:
